vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - csstools.postcss
    - clinyong.vscode-css-modules
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - christian-kohler.path-intellisense
