vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - csstools.postcss
    - clinyong.vscode-css-modules
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - christian-kohler.path-intellisense
    - mikestead.dotenv
tasks:
  - name: Install Dependencies
    init: >
      npm install --prefix /workspace/enager/package &&
      gp sync-done install
  - name: Start Dev Server
    init: gp sync-await install
    command: npm run dev --prefix /workspace/enager/package
