#!/usr/bin/env python3
from plumbum import cli, local

# Alias function to npm install command with the CWD in /package
install = local.cmd.npm.with_cwd("package")["install"]

class App(cli.Application):
    DESCRIPTION = "Install dependencies"

    def main(self):
        install()

if __name__ == "__main__":
    App.run()