#!/usr/bin/env python3
from plumbum import cli, local, colors

# Alias function to npx command with the CWD in /package
next = local.cmd.npx.with_cwd("package")["next"]

class App(cli.Application):
    prod = cli.Flag(["prod", "production"], help = "Build and compile for production")
    DESCRIPTION = "Start application. Defaults to dev server."

    def main(self):
        if self.prod:
            print(colors.info | "Building application")
            next("build", "--verbose")
            print(colors.success | "Starting application")
            next("start")
        else:
            print(colors.success | "Running dev server on port 3000")
            print("https://localhost:3000")
            next("dev")

if __name__ == "__main__":
    App.run()